services:
  - type: web
    name: react-job-portal-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        value: dtgsdprcl
      - key: DB_URL
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_EXPIRE
        value: 7d
      - key: COOKIE_EXPIRE
        value: 7
      - key: FRONTEND_URL
        value: https://frontend-swart-chi-76.vercel.app
